import fs from 'fs'
import path from 'path'

/**
 * Pre-generated blur data loaded once at startup.
 * Generated by `npm run generate-blur` and committed to the repo.
 * This avoids fetching full images from Blob at build time.
 */
let blurCache: Record<string, string> | null = null

function getBlurCache(): Record<string, string> {
  if (blurCache) return blurCache

  const jsonPath = path.join(process.cwd(), 'blur-data.json')
  try {
    const raw = fs.readFileSync(jsonPath, 'utf8')
    blurCache = JSON.parse(raw)
    return blurCache!
  } catch {
    console.warn('blur-data.json not found. Run `npm run generate-blur` to generate it.')
    blurCache = {}
    return blurCache
  }
}

/**
 * Look up the blur data URL for an image path.
 *
 * Matches by filename since frontmatter paths are local (/images/recipes/foo.jpeg)
 * but may be transformed to blob URLs before reaching here.
 */
export async function getBlurDataURL(imagePath: string): Promise<string | undefined> {
  const cache = getBlurCache()

  // Direct lookup (local path like /images/recipes/foo.jpeg)
  if (cache[imagePath]) {
    return cache[imagePath]
  }

  // Fallback: match by filename (handles blob URLs or other path variations)
  const filename = imagePath.split('/').pop()
  if (filename) {
    const localKey = `/images/recipes/${filename}`
    if (cache[localKey]) {
      return cache[localKey]
    }
  }

  return undefined
}

export async function getImageWithBlur(imagePath: string) {
  const blurDataURL = await getBlurDataURL(imagePath)
  return {
    src: imagePath,
    blurDataURL,
  }
}
